drop table if exists Person;

create table Person(
                       id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       name varchar(30) NOT NULL,
                       age int CHECK(age>0)
);


insert into Person( name, age)
values('Вадим', 49);

select * from Person;