drop table if exists Item;
drop table if exists Person;

create table Person(
                       id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       name varchar(30) NOT NULL,
                       age int CHECK(age>0)
);


insert into Person( name, age)
values('Вадим', 49),
      ('Елена', 43),
      ('Кира', 21);

select * from Person;

create table Item(
                     id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                     name varchar(130) NOT NULL,
                     person_id int REFERENCES Person (id)
);

insert into Item (name, person_id)
values('Лыжи', 1),
      ('Телевизор', 1),
      ('Смартфон', 1),
      ('Куртка', 2),
      ('Лак', 2);

select * from Item;