drop table if exists Person_Subscribetion;
drop table if exists Subscribetion;
drop table if exists Item;
drop table if exists Passport;
drop table if exists Person;

create table Person(
                       id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       name varchar(30) NOT NULL,
                       age int CHECK(age>0)
);


insert into Person( name, age)
values('Вадим', 49),
      ('Елена', 43),
      ('Кира', 21);

select * from Person;

create table Item(
                     id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                     name varchar(130) NOT NULL,
                     person_id int REFERENCES Person (id)  ON DELETE CASCADE
);

insert into Item (name, person_id)
values('Лыжи', 1),
      ('Телевизор', 1),
      ('Смартфон', 1),
      ('Куртка', 2),
      ('Лак', 2);

select * from Item;

create table Passport (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    person_id int UNIQUE REFERENCES Person(id) ON DELETE CASCADE ,
    passport_number varchar(10) NOT NULL

);

insert into Passport(passport_number, person_id)
    values('XXXD567567', 1), ('XXXA999678', 2);

select * from Passport;

create table Subscribetion(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(30) NOT NULL UNIQUE
);

insert into Subscribetion(name)
values ('Новости'), ('Акции');

create table Person_Subscribetion(
    person_id int not null REFERENCES Person(id),
    subscribetion_id int not null REFERENCES Subscribetion(id),
    CONSTRAINT Person_Group_PK PRIMARY KEY (person_id, subscribetion_id)
);

insert into Person_Subscribetion(person_id, subscribetion_id) VALUES
(1,1), (1,2), (2,2);

select * from Person_Subscribetion;